---
- name: Ensuring config directories exist
  file:
    path: "{{ config_directory }}/{{ item.key }}"
    state: "directory"
    mode: "0770"
  become: true
  with_dict: "{{ mariadb_services }}"

- name: Create mariadb log dir
  file:
    path: "/var/log/mariadb"
    state: "directory"
    mode: "0755"
  become: true

- name: Copying over wsrep-notify.sh
  template:
    src: "wsrep-notify.sh.j2"
    dest: "{{ config_directory }}/mariadb/wsrep-notify.sh"
    mode: "0770"
  become: true

- name: Copying over galera.cnf
  vars:
    service_name: "mariadb"
    service: "{{ mariadb_services[service_name] }}"
  template:
    src: "galera.cnf.j2"
    dest: "{{ config_directory }}/{{ service_name }}/galera.cnf"
    mode: "0660"
  become: true
  notify:
    - restart mariadb

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  with_dict: "{{ mariadb_services }}"
  notify:
    - "restart {{ item.key }}"
