- name: Create file share_image dir
  become: true
  file:
    path: "{{ share_mount_dir }}/voi/share_image"
    state: directory
    mode: 0755

- name: copy share images file
  block:
  - name: copy 5G init share images file
    become: true
    copy:
      src: "5GDISK.qcow2"
      dest: "{{ share_mount_dir }}/voi/share_image/5GDISK.qcow2"

  - name: copy 10G init share images file
    become: true
    copy:
      src: "10GDISK.qcow2"
      dest: "{{ share_mount_dir }}/voi/share_image/10GDISK.qcow2"

  - name: copy 50G init share images file
    become: true
    copy:
      src: "50GDISK.qcow2"
      dest: "{{ share_mount_dir }}/voi/share_image/50GDISK.qcow2"
