---
- name: copy lvm conf file
  copy:
    src: lvm.conf
    dest: /etc/lvm/lvm.conf

- name: 查看 pv 是否存在
  shell: "vgs | grep {{ local_vg_name }} | wc -l"
  register: vg_exist

- name: 生成创建命令
  set_fact:
    pv_volume: "{% for pv in local_device %} {{ pv }} {% if not loop.last %} {% endif %}{% endfor %}"
  when:
    - vg_exist.stdout == "0"
    - local_device | length >= 1

- name: 生成创建命令
  block:
    - name: Get starting sector
      shell: "sudo parted {{ system_device }} unit s print free | awk '/Free Space/ {last=$1} END {print last}'"
      register: start_sector

    - name: Create data partition
      shell: "parted -s {{ system_device }} mkpart primary ext4 {{ start_sector.stdout }} 100%"
      become: true

    - name: Get new partition name
      shell: ls {{ system_device }}* | grep -P '{{ system_device }}\d+$' | tail -1
      register: data_part_name

    - name: Format new partition
      filesystem:
        fstype: ext4
        force: true
        dev: "{{ data_part_name.stdout }}"

    - name: Generate creation command
      set_fact:
        pv_volume: "{{ data_part_name.stdout }}"
  when:
    - vg_exist.stdout == "0"
    - local_device | length == 0

- name: 创建 pv
  become: true
  shell: "pvcreate {{ pv_volume }}"
  when:
    - vg_exist.stdout == "0"

- name: 创建 vg
  become: true
  shell: "vgcreate {{ local_vg_name }} {{ pv_volume }}"
  when: 
    - vg_exist.stdout == "0"

- name: 查看 trochilus lv 卷是否创建
  shell: "lvs | grep {{ local_trochilus_lv_name }} | wc -l"
  register: trochilus_lv_exist

- name: 创建 trochilus 逻辑卷
  become: true
  shell: "lvcreate -y -L {{ trochilus_lv_size }} -n {{ local_trochilus_lv_name }} {{ local_vg_name }}"
  when:
    - trochilus_lv_exist.stdout == "0"

- name: 格式化 trochilus 逻辑卷
  shell: "mkfs.ext4 /dev/{{ local_vg_name }}/{{ local_trochilus_lv_name }}"
  when:
    - trochilus_lv_exist.stdout == "0"

- name: Mount trochilus logical volume
  mount:
    path: "{{ desktop_mount_dir }}"
    src: "/dev/{{ local_vg_name }}/{{ local_trochilus_lv_name }}"
    fstype: ext4
    state: mounted

- name: 查看 net lv 卷是否创建
  shell: "lvs | grep {{ local_net_lv_name }} | wc -l"
  register: net_lv_exist

- name: 创建 net 逻辑卷
  become: true
  shell: "lvcreate -y -L {{ share_lv_size }} -n {{ local_net_lv_name }} {{ local_vg_name }}"
  when:
    - net_lv_exist.stdout == "0"

- name: 格式化 net 逻辑卷
  shell: "mkfs.ext4 /dev/{{ local_vg_name }}/{{ local_net_lv_name }}"
  when:
    - net_lv_exist.stdout == "0"

- name: Mount share net logical volume
  mount:
    path: "{{ share_mount_dir }}"
    src: "/dev/{{ local_vg_name }}/{{ local_net_lv_name }}"
    fstype: ext4
    state: mounted
  when: groups['glusterfs'] | length < 3

- name: Apply role glusterfs
  import_role:
    name: glusterfs
  when: 
    - enable_glusterfs | bool
