---
- name: copy lvm conf file
  copy:
    src: lvm.conf
    dest: /etc/lvm/lvm.conf

- name: local_device 和 share_device都为空时 默认使用系统盘的剩余空间
  block:
    - name: Get starting sector
      shell: "sudo parted {{ system_device }} unit s print free | awk '/Free Space/ {last=$1} END {print last}'"
      register: start_sector

    - name: Create data partition
      shell: "sudo parted -s {{ system_device }} mkpart primary ext4 {{ start_sector.stdout }} 100%"
      become: true

    - name: Get partition list
      shell: "ls {{ system_device }}*"
      register: partition_list

    - name: Determine last partition number
      set_fact:
        partition_num: "{{ partition_list.stdout_lines[-1][-1] }}"
      when: partition_list.stdout_lines | length > 0

    - name: Create data partition
      shell: "parted -s {{ system_device }} set {{ partition_num}} lvm on"
      when: partition_num is defined
      become: true

    - name: Generate creation command
      set_fact:
        pv_volume: "{{ system_device }}{{ partition_num }}"
      when: partition_num is defined
  when:
    - local_net_lv_name not in ansible_lvm.lvs
    - local_device | length == 0
    - share_device | length == 0

- name: 当share单独使用时创建lv挂载
  block:
    - name: 单硬盘时创建share的vg
      lvg:
        vg: "{{ local_share_vg_name }}"
        pvs: "{{ pv_volume }}"
      when: 
        - local_share_vg_name not in ansible_lvm.vgs
        - pv_volume is defined

    - name: 创建share的vg
      lvg:
        vg: "{{ local_share_vg_name }}"
        pvs: "{% for disk in share_device %}{{ disk }}{% if not loop.last %},{% endif %}{% endfor %}"
      when: 
        - local_share_vg_name not in ansible_lvm.vgs
        - pv_volume is not defined
    
    - name: 判断share_lv是否存在
      set_fact:
        share_lvbool: "{{ local_net_lv_name in ansible_lvm.lvs }}"

    - name: 创建share的lv
      lvol:
        vg: "{{ local_share_vg_name }}"
        lv: "{{ local_net_lv_name }}"
        size: "{{ share_lv_size }}"
      when: not share_lvbool | bool
    
    - name: 格式化share的lv
      filesystem:
        fstype: ext4
        dev: /dev/{{ local_share_vg_name }}/{{ local_net_lv_name }}
        force: true
      when: not share_lvbool | bool
  when: 
    - share_device | length != 0 or( share_device | length == 0 and fsd_deploy_mode == 'voi')
    - inventory_hostname in groups['glusterfs']

- name: 非单voi时创建local资源
  block:
    - name: 单硬盘时创建local的vg
      lvg:
        vg: "{{ local_vg_name }}"
        pvs: "{{ pv_volume }}"
      when: 
        - local_vg_name not in ansible_lvm.vgs
        - pv_volume is defined

    - name: 创建local的vg
      lvg:
        vg: "{{ local_vg_name }}"
        pvs: "{% for disk in local_device %}{{ disk }}{% if not loop.last %},{% endif %}{% endfor %}"
      when: 
        - local_vg_name not in ansible_lvm.vgs
        - pv_volume is not defined

    - name: 判断local的lv是否存在
      set_fact:
        local_lvbool: "{{ local_trochilus_lv_name in ansible_lvm.lvs }}"

    - name: 创建local的lv
      lvol:
        vg: "{{ local_vg_name }}"
        lv: "{{ local_trochilus_lv_name }}"
        size: "{{ trochilus_lv_size }}"
      when: not local_lvbool | bool
    
    - name: 格式化local的lv
      filesystem:
        fstype: ext4
        dev: /dev/{{ local_vg_name }}/{{ local_trochilus_lv_name }}
        force: true
      when: not local_lvbool | bool

    - name: cat trochilus UUID
      shell: "blkid | grep {{ local_vg_name }}-{{ local_trochilus_lv_name }} | awk -F' ' '{print $2}'"
      register: trochilus_uuid
      failed_when: trochilus_uuid.stdout == ""

    - name: Mount trochilus logical volume
      mount:
        path: "{{ desktop_mount_dir }}"
        src: "{{ trochilus_uuid.stdout | replace('\"', '') }}"
        fstype: ext4
        state: mounted
  when: fsd_deploy_mode != 'voi'

- name: 当share不单独使用磁盘时控制节点创建vg
  block:
    - name: 查看 net lv 卷是否创建
      shell: "lvs | grep {{ local_net_lv_name }} | wc -l"
      register: net_lv_exist

    - name: 创建 net 逻辑卷
      become: true
      shell: "lvcreate -y -L {{ share_lv_size }} -n {{ local_net_lv_name }} {{ local_vg_name }}"
      when:
        - net_lv_exist.stdout == "0"

    - name: 格式化 net 逻辑卷
      shell: "mkfs.ext4 /dev/{{ local_vg_name }}/{{ local_net_lv_name }}"
      when:
        - net_lv_exist.stdout == "0"

  when:
    - share_device | length == 0
    - fsd_deploy_mode != 'voi'
    - inventory_hostname in groups['glusterfs']

- name: Apply role glusterfs
  import_role:
    name: glusterfs
  when: 
    - enable_glusterfs | bool
