---
- name: 获取 osd 数量
  shell: systemctl | grep running | grep osd@ | wc -l
  register: osd_num

- name: 获取可分配的大页数量
  set_fact:
    hugepages_total: >-
      {% if ansible_memtotal_mb >= 65536 %}
        {{ (ansible_memtotal_mb - reserved_osd_memory_mb * osd_num.stdout | int - reserved_mds_memory_mb - reserved_mon_memory_mb - reserved_system_memory_mb - reserved_host_memory_mb) // 2 | int }}
      {% elif ansible_memtotal_mb >= 32768 %}
        16384
      {% else %}
        4096
      {% endif %}

- name: 分配大页内存
  become: true
  shell: echo {{ hugepages_total }} > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages

- name: openEuler Replace GRUB_CMDLINE_LINUX in /etc/default/grub
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX=.*"
    line: "GRUB_CMDLINE_LINUX=\"rd.lvm.lv=openeuler/root crashkernel=512M default_hugepagesz={{ hugepages_size }} hugepages={{ hugepages_total }} kvm.nx_huge_pages=off\""
    state: present
  become: True

- name: openEuler 修改 grub 配置文件配置内存大页重启生效
  become: true
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg
