---
- name: Create trochilus dir
  become: true
  file:
    path: "{{ share_disk_mount_path }}"
    state: directory
    mode: 0755

- import_tasks: mount_cephfs.yml
  when:
    - enable_ceph | bool
    - not enable_local | bool

- import_tasks: create_vg_volume.yaml
  when:
    - enable_lvm | bool

- import_tasks: create_local_volume.yml
  when:
    - enable_local | bool

- import_tasks: hugepages_config.yml
  when:
    - enable_hugepages | bool

- import_tasks: set_voi_data_device.yml
  when: only_deploy_voi | bool
  run_once: True

- import_tasks: set_voi_virt_nic.yml
  when: only_deploy_voi | bool
  run_once: True
