---
- name: Create file share dir
  become: true
  file:
    path: "{{ share_mount_dir }}"
    state: directory
    mode: 0755

- name: only deploy voi mount data device
  block: 
  - name: Create directory if not exists
    file:
      name: "{{ voi_data_directory }}"
      state: directory
      owner: root
      group: root
      mode: '0751'

  - name: format datanode disks
    filesystem: 
      fstype: ext4
      force: true
      dev: "{{ voi_data_device }}"

  - name: cat disk UUID
    shell: blkid | grep {{ voi_data_device }} | awk -F' ' '{print $2}'
    register: disk_uuid

  - name: mount datanode disks
    mount:
      path: "{{ voi_data_directory }}"
      src: "{{ disk_uuid.stdout | replace('\"', '') }}"
      fstype: ext4
      opts: "defaults,noatime,nobarrier"
      state: mounted
  when: 
    - ansible_facts.mounts | selectattr('mount', '==', voi_data_directory) | list | length == 0 
    - voi_data_device != ""

- import_tasks: copy_share_image.yml
