---

- name: Ensuring config directories exist
  file:
    path: "{{ config_directory }}/{{ item.key }}"
    state: "directory"
    mode: "0775"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ redis_services }}"

- name: Copying over redis config files
  vars:
    service_name: "redis"
    service: "{{ redis_services[service_name] }}"
  template:
    src: "redis.conf.j2"
    dest: "{{ config_directory }}/redis/redis.conf"
    mode: "0664"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart redis container
  #   - Restart redis-sentinel container

- name: Copying over redis-sentinel config files
  vars:
    service_name: "redis-sentinel"
    service: "{{ redis_services[service_name] }}"
  template:
    src: "redis-sentinel.conf.j2"
    dest: "{{ config_directory }}/redis-sentinel/redis.conf"
    mode: "0664"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart redis-sentinel container

- name: Ensuring redis log directories exist
  file:
    path: "/var/log/redis"
    state: "directory"
    mode: "0775"
  become: true

- name: Touch redis log file and set permissions
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0666
    state: touch
  loop:
    - /var/log/redis/redis.log
    - /var/log/redis/redis-sentinel.log

- include_tasks: check-containers.yml
  when: redis_action != "config"
