---
- import_tasks: recovery_db.yaml

- import_tasks: remove_vm.yaml

- import_tasks: remove_net.yaml

- name: get voi resource
  shell: "ls {{ desktop_mount_dir }}/voi -I share_image"
  register: files_list

- name: remove voi resource
  file:
    path: "{{ desktop_mount_dir }}/voi/{{ item }}"
    state: absent
  with_items:
    - "{{ files_list.stdout_lines }}"

- name: remove extra voi resource
  file:
    path: "{{ desktop_mount_dir }}/{{ item }}"
    state: absent
  with_items:
    - "111"
    - "p2v"

- name: Remove redis container
  kolla_docker:
    name: "{{ item }}"
    action: remove_container
  with_items:
    - "redis"
    - "redis_sentinel"

- name: remove redis volume
  kolla_docker:
    action: remove_volume
    name: redis_data

- name: remove redis config
  file:
    path: "{{ config_directory }}/{{ item }}"
    state: absent
  with_items:
    - "redis"
    - "redis-sentinel"

- name: Apply role redis
  import_role:
    name: redis

- name: remove trochilus config
  file:
    path: "{{ config_directory }}/trochilus"
    state: absent

- name: Apply role trochilus
  import_role:
    name: trochilus

- name: remove fsd config
  file:
    path: "{{ config_directory }}/fsd"
    state: absent

- name: restart btserver container
  kolla_docker:
    name: "{{ item }}"
    action: restart_container
  with_items:
    - "btserver"
    - "btserver_tracker"

- name: Apply role fsd
  import_role:
    name: fsd

- name: restart redis container
  kolla_docker:
    name: "{{ item }}"
    action: restart_container
  with_items:
    - "redis"
    - "redis_sentinel"
