---
- import_tasks: recovery_db.yaml

- import_tasks: remove_vm.yaml

- name: remove fsd config
  file:
    path: "{{ config_directory }}/fsd"
    state: absent

- name: remove voi all file
  file:
    path: "{{ trochilus_voi_base_path }}"
    state: absent

- name: remove 111
  file:
    path: "{{ desktop_mount_dir }}/111"
    state: absent

- name: remove p2v
  file:
    path: "{{ desktop_mount_dir }}/p2v"
    state: absent

- import_tasks: remove_net.yaml

- name: Apply role trochilus
  import_role:
    name: trochilus

- name: Apply role fsd
  import_role:
    name: fsd
