---
- name: delete trochilus and fsd databases
  mysql_db: 
    login_host: "{{ default_internal_server_visit_ip }}"
    login_port: "{{ mariadb_external_listen_port }}"
    login_user: "{{ mariadb_root_username }}"
    login_password: "{{ mariadb_root_password }}"
    name: "{{ item }}"
    state: "absent"
  run_once: True
  delegate_to: "{{ groups['trochilus-api'][0] }}"
  loop:
    - "{{ trochilus_mariadb_dataname }}"
    - "klcloud_fsd_edu"
    - "xxl_job"
