- name: get all vm id
  shell: "docker exec -it libvirt virsh list --all --uuid"
  register: all_vm_uuid

- name: destroy all vm
  shell: "docker exec -it libvirt virsh destroy {{ item }}"
  with_items: "{{ all_vm_uuid.stdout_lines }}"
  ignore_errors: true

- name: undefine all vm
  shell: "docker exec -it libvirt virsh undefine {{ item }} --nvram"
  with_items: "{{ all_vm_uuid.stdout_lines }}"
