---
- name: Create Glusterfs Metadata Dir
  file:
    path: "{{ gluster_metadata_path }}"
    state: directory
    mode: 0755

- name: cat net UUID
  shell: "blkid | grep {{ local_vg_name }}-{{ local_net_lv_name }} | awk -F' ' '{print $2}'"
  register: net_uuid
  when: 
    - share_device | length == 0

- name: cat share UUID
  shell: "blkid /dev/{{ local_share_vg_name }}/{{ local_net_lv_name }} | awk -F' ' '{print $2}'"
  register: net_uuid
  when: 
    - share_device | length != 0

- name: Mount Glusterfs Metadata Lvm To Glusterfs Metadata Path
  mount:
    src: "{{ net_uuid.stdout | replace('\"', '') }}"
    path: "{{ gluster_metadata_path }}"
    state: "mounted"
    fstype: ext4

- name: Check Mounting
  shell: mountpoint -q {{ gluster_metadata_path }}
  register: mountpoint_info
  failed_when: mountpoint_info.rc != 0
