---
- name: Create Glusterfs Metadata Dir
  file:
    path: "{{ gluster_metadata_path }}"
    state: directory
    mode: 0755

- name: Create xfs filesystem
  filesystem:
    fstype: xfs
    dev: "/dev/{{ local_vg_name }}/{{ local_net_lv_name }}"

- name: Mount Glusterfs Metadata Lvm To Glusterfs Metadata Path
  mount:
    src: "/dev/{{ local_vg_name }}/{{ local_net_lv_name }}"
    path: "{{ gluster_metadata_path }}"
    state: "mounted"
    fstype: xfs

- name: Check Mounting
  shell: mountpoint -q {{ gluster_metadata_path }}
  register: mountpoint_info
  failed_when: mountpoint_info.rc != 0
