---
- name: Check if chrony is installed
  command: "rpm -qa chrony" 
  register: chrony_check
  changed_when: false
  args:
    warn: false

- name: Install chrony
  package:
    name: chrony
  when: chrony_check.rc > 1

- name: restart chronyd.service
  systemd:
    name: chronyd.service
    state: restarted

- name: Flush handlers
  meta: flush_handlers

- name: update time
  shell: chronyc -a makestep
