---
- name: Install chrony
  package:
    name: chrony

- name: Copy chrony conf
  template:
    src: chrony.conf.j2
    dest: "/etc/chrony.conf"
    mode: 0644
  notify: Restart chronyd

- name: disable timedatectl ntp
  shell: |
    timedatectl set-ntp no
  ignore_errors: true

- name: Flush handlers
  meta: flush_handlers

- name: update time
  shell: chronyc -a makestep
  ignore_errors: true
