---
- name: Check if chrony is installed
  command: "rpm -qa chrony"
  register: chrony_check
  changed_when: false
  args:
    warn: false

- name: Install chrony
  package:
    name: chrony
  when: chrony_check.rc != 0

- name: Copy chrony conf
  template:
    src: chrony.conf.j2
    dest: "/etc/chrony.conf"
    mode: 0644
  notify: Restart chronyd

- name: disable timedatectl ntp
  shell: |
    timedatectl set-ntp no
  ignore_errors: true

- name: Flush handlers
  meta: flush_handlers

- name: update time
  shell: chronyc -a makestep
  ignore_errors: true
