---
- name: Generate /etc/hosts for all of the nodes
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE GENERATED HOSTS"
    block: |
        {% for host in groups['baremetal'] %}
        {% set api_interface = hostvars[host]['api_interface'] %}
        {% if 'ansible_' + api_interface in hostvars[host] %}
        {% set hostnames = [hostvars[host]['ansible_nodename'], hostvars[host]['ansible_hostname']] %}
        {{ hostvars[host]['ansible_' + api_interface]['ipv4']['address'] }} {{ hostnames | unique | join(' ') }}  {{ docker_register_domain }}
        {% endif %}
        {% endfor %}
  become: True

- name: 创建 /etc/docker 目录
  become: true
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: 确认 Docker 配置是否有修改
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    mode: 0644
  register: configuration_result

- name: 重新加载 daemon
  systemd:
    daemon_reload: yes

- name: 启动/重启 Docker
  service:
    name: docker
    state: restarted
    enabled: yes
  when: 
  - configuration_result.changed

- name: Run openEuler offline-rpm-repo 容器
  docker_container: 
    image: "{{ docker_image_repository }}/openeuler-offline-rpm-repo:{{ docker_image_tag }}"
    name: openeuler-offline-rpm-repo
    state: started
    restart: yes
    restart_policy: always
    ports:
      - "{{ offline_deb_repo_port }}:80"
