---
- name: Gets the content of the specified row
  shell: ceph osd  crush rule dump replicated_rule -f yaml
  register: crush_rule
  delegate_to: "{{ groups['ceph-osds'][0] }}"
  run_once: true

- name: create and set aio crush_rules
  delegate_to: "{{ groups['ceph-osds'][0] }}"
  run_once: true
  block:
    - name: Export the binary file of ceph Crushmap
      command: ceph osd getcrushmap -o /tmp/crushmap.bin

    - name: Parse the crushmap binary
      command: crushtool -d /tmp/crushmap.bin -o /tmp/crushmap.txt

    - name: Edit modifies the isolation domain to osd
      lineinfile:
        path: /tmp/crushmap.txt
        regexp: "step chooseleaf firstn 0 type host"
        line: "        step chooseleaf firstn 0 type osd"
      when: ceph_aio

    - name: Edit modifies the isolation domain to host
      lineinfile:
        path: /tmp/crushmap.txt
        regexp: "step chooseleaf firstn 0 type osd"
        line: "        step chooseleaf firstn 0 type host"
      when: not ceph_aio

    - name: Convert back to binary crushmap-new.bin
      command: crushtool -c /tmp/crushmap.txt -o /tmp/crushmap-new.bin

    - name: Update binaries to ceph
      command: ceph osd setcrushmap -i /tmp/crushmap-new.bin

  when: (not ceph_aio and 'host' != (crush_rule.stdout | from_yaml).steps[1].type) or (ceph_aio and 'osd' != (crush_rule.stdout | from_yaml).steps[1].type)