- name: bakup btserver config file
  vars:
    folder_name: btserver
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
  file:
    src: "{{ config_directory }}/{{ folder_name }}"
    dest: "{{ upgrade_resource_path }}/{{ folder_name }}-{{ timestamp }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: upgade btserver service
  import_role:
    name: btserver

