---
- name: Copy image to remote host
  copy:
    src: "{{ upgrade_image_file }}"
    dest: "{{ upgrade_image_file }}"
  delegate_to: localhost
  run_once: true

- name: Load upgrade image
  shell: "docker load -i {{ upgrade_image_file }}"

- name: Bakup databses
  shell: /bin/bash {{ config_directory }}/mariadb/mysql_backup.sh
  delegate_to: localhost
  run_once: true

- name: Create file upgarde dir
  become: true
  file:
    path: "{{ config_directory }}/upgrade/"
    state: directory
    mode: 0755

- import_tasks: libvirt.yml
  when: "'libvirt' in upgrade_service"

- import_tasks: trochilus.yml
  when: "'trochilus' in upgrade_service"

- import_tasks: guest-service.yml
  when: "'guest-service' in upgrade_service"

- import_tasks: btserver.yml
  when: "'btserver' in upgrade_service"

- import_tasks: fsd.yml
  when: "'fsd' in upgrade_service"
