- name: bakup trochilus config file
  vars:
    folder_name: trochilus
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
  file:
    src: "{{ config_directory }}/{{ folder_name }}"
    dest: "{{ upgrade_resource_path }}/{{ folder_name }}-{{ timestamp }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  run_once: true
  delegate_to: "{{ groups['trochilus-api'][0] }}"

- name: upgade trochilus service
  import_role:
    name: trochilus
