groups:
  - name: service.rule
    rules:
    - record: TWatch:Service::Opentracker
      expr: docker_container_service_status{name="btserver_tracker", state="running"}

    - record: TWatch:Service::Torrent
      expr: docker_container_service_status{name="btserver", state="running"}

    - record: TWatch:Service::Emqx
      expr: docker_container_service_status{name="emqx", state="running"}

    - record: TWatch:Service::FsdJob
      expr: docker_container_service_status{name="fsd_job", state="running"}

    - record: TWatch:Service::FsdWeb
      expr: docker_container_service_status{name="fsd_web", state="running"}

    - record: TWatch:Service::Mariadb
      expr: docker_container_service_status{name="mariadb", state="running"}

    - record: TWatch:Service::Websockify
      expr: docker_container_service_status{name="websockify", state="running"}

    - record: TWatch:Service::Collectd
      expr: node_systemd_unit_state{name="collectd.service",state="active"}

    - record: TWatch:Service::Redis
      expr: docker_container_service_status{name="redis", state="running"}

    - record: TWatch:Service::Smbd
      expr: node_systemd_unit_state{name="smbd.service",state="active"}

    - record: TWatch:Service::Nginx
      expr: docker_container_service_status{name="nginx", state="running"}

    - record: TWatch:Service::TrochilusApi
      expr: docker_container_service_status{name="trochilus_api", state="running"}

    - record: TWatch:Service::TrochilusAgent
      expr: docker_container_service_status{name="trochilus_agent", state="running"}

    - record: TWatch:Service::Libvirtd
      expr: docker_container_service_status{name="libvirtd", state="running"}

    - record: TWatch:Service::Dnsmasq
      expr: docker_container_service_status{name="dnsmasq", state="running"}

    - record: TWatch:Service::Prometheus
      expr: docker_container_service_status{name="prometheus", state="running"}

    - record: TWatch:Service::NodeExporter
      expr: docker_container_service_status{name="node_exporter", state="running"}

    - record: TWatch:Service::Alertmanager
      expr: docker_container_service_status{name="alertmanager", state="running"}

    - record: TWatch:Service::Pushgateway
      expr: docker_container_service_status{name="pushgateway", state="running"}

    - record: TWatch:Service::Consul
      expr: docker_container_service_status{name="consul", state="running"}
