---
- name: Get the last in network IP address
  set_fact:
    manage_ip_last_two_octets: "{{ external_manage_ip.split('.')[2:] | join('.') }}"

- name: Assembling internal IP
  set_fact:
    manage_internal_ip: "169.168.{{ manage_ip_last_two_octets }}"

- name: Modifying network connections
  become: True
  shell: "nmcli connection modify {{ api_interface }} +ipv4.addresses {{ manage_internal_ip }}/24"

- name: Restart network crad
  shell: "nmcli connection down {{ api_interface }} && nmcli connection up {{ api_interface }}"

- name: Replace the IP in the host file
  replace:
    path: "{{ inventory_file }}"
    regexp: '^((?!external_manage_ip=).)*{{ hostvars[item].external_manage_ip }}'
    replace: '{{ hostvars[item].manage_internal_ip }}'
    backup: yes
  run_once: True
  delegate_to: "{{ groups['baremetal'][0] }}"
  with_items: "{{ groups['baremetal'] }}"

- name: Restart veth-setup service
  systemd:
    name: veth-setup.service
    state: restarted
    enabled: True
  when: enable_single_net | bool