---
- name: Restart emqx container
  vars:
    service_name: "emqx"
    service: "{{ emqx_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    user: "{{ service.user }}"
    
