---
- name: Restart prometheus container
  vars:
    service_name: "prometheus"
    service: "{{ prometheus_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    command: "{{ service.command }}"
    dimensions: "{{ service.dimensions }}"

- name: Restart prometheus-pushgateway container
  vars:
    service_name: "prometheus-pushgateway"
    service: "{{ prometheus_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    command: "{{ service.command }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"

- name: Restart prometheus-alertmanager container
  vars:
    service_name: "prometheus-alertmanager"
    service: "{{ prometheus_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    command: "{{ service.command }}"
    dimensions: "{{ service.dimensions }}"

- name: Restart prometheus-node-exporter container
  vars:
    service_name: "prometheus-node-exporter"
    service: "{{ prometheus_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    command: "{{ service.command }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"

- name: Restart prometheus-collectd-exporter container
  vars:
    service_name: "prometheus-collectd-exporter"
    service: "{{ prometheus_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    command: "{{ service.command }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"

- name: Restart prometheus-host-exporter container
  vars:
    service_name: "prometheus-host-exporter"
    service: "{{ prometheus_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    command: "{{ service.command }}"
    privileged: "{{ service.privileged | default(False) }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"

- name: Restart prometheus-docker-exporter container
  vars:
    service_name: "prometheus-docker-exporter"
    service: "{{ prometheus_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"

- name: Restart prometheus-consul container
  vars:
    service_name: "prometheus-consul"
    service: "{{ prometheus_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    command: "{{ service.command }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"

- name: Restart prometheus-thanos-sidecar container
  vars:
    service_name: "prometheus-thanos-sidecar"
    service: "{{ prometheus_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    command: "{{ service.command }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"

- name: Restart prometheus-thanos-query container
  vars:
    service_name: "prometheus-thanos-query"
    service: "{{ prometheus_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    command: "{{ service.command }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"