---
ceph_local_ip: "{% if ceph_public_interface == api_interface %}{{ inventory_hostname }}{% else %}{{ hostvars[inventory_hostname]['ansible_' + ceph_public_interface]['ipv4']['address'] }}{% endif %}"
desktop_mount_shell_dir: "/etc/ceph/cephmount"
cephmount_service_dir: "/usr/lib/systemd/system/"

create_local_part: "{% if local_device | length == 0 %}true{% else %}false{% endif %}"
trochilus_lv_size: "{{ vdi_storage_num }}G"
share_lv_size: "{{ vdi_file_storage_num + cloud_disk_num + voi_storage_num }}G"

disk_name: "{% for key in ansible_facts.devices %}{% if ansible_facts.devices[key].partitions | length > 0 %}{{ key }}{% endif %}{% endfor %}"
share_disk_mount_path: "{% if deploy_comm | bool %}{{ desktop_mount_dir }}{% elif deploy_edu | bool %}{{ share_mount_dir }}{% endif %}"
