---
- name: Check seafile containers
  become: true
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
  with_dict: "{{ seafile_services }}"
  notify:
    - "Restart seafile container"
