- name: Ensuring config directories exist
  file:
    path: "{{ config_directory }}/haproxy"
    state: "directory"
    mode: "0775"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ haproxy_services }}"

- name: Copying over haproxy.cfg
  vars:
    service: "{{ haproxy_services['haproxy'] }}"
  template:
    src: "haproxy.cfg.j2"
    dest: "{{ config_directory }}/haproxy/haproxy.cfg"
    mode: "0664"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart haproxy container

- include_tasks: keepalived.yml
  when:
    - enable_keepalived | bool
    - inventory_hostname in groups['keepalived']
