---
- name: check swap 文件是否存在
  stat: 
    path: "{{ swap_file_path }}"
  register: swap_file

- name: 创建 swapfile 文件
  become: True
  shell: "dd if=/dev/zero of={{ swap_file_path }} bs={{ swap_file_block_size }} count={{ swap_file_true }}"
  when:
    - not swap_file.stat.exists

- name: 修改 swapfile 权限
  file:
    path: "{{ swap_file_path }}"
    mode: 600

- name: 执行 mkswap 命令
  become: True
  shell: "mkswap {{ swap_file_path }}"
  when:
    - not swap_file.stat.exists

- name: 打开 swap 分区
  become: True
  shell: "swapon {{ swap_file_path }}"
  when:
    - not swap_file.stat.exists

- name: 设置开机挂载 swap
  become: True
  lineinfile:
    dest: /etc/fstab
    line: "{{ swap_file_path }} swap swap defaults 0 0"
    state: present
