---
- name: 复制resize_bcache_minimun.service
  copy:
    src: resize_bcache_minimum.service
    dest:  /usr/lib/systemd/system/resize_bcache_minimum.service
  when:
    - inventory_hostname in groups['storage']

- name: 复制 resize_bcache_minimum 文件
  copy:
    src: resize_bcache_minimum
    dest:  /usr/local/bin/resize_bcache_minimum
    mode: 0755
  when:
    - inventory_hostname in groups['storage']

- name: Reload systemctl and enable resize_bcache_minimum service
  become: true
  systemd:
    name: resize_bcache_minimum
    daemon_reload: true
    enabled: true
  when:
    - inventory_hostname in groups['storage']

- name: Restart systemctl and enable resize_bcache_minimum service
  become: true
  systemd:
    name: resize_bcache_minimum
    state: restarted
  when:
    - inventory_hostname in groups['storage']
