---
- name: Ensuring btserver config directories exist
  file:
    path: "{{ config_directory }}/btserver"
    state: "directory"
    mode: "0775"
  become: true

- name: copy opentracker.conf conf file
  template:
    src: opentracker.conf.j2
    dest: "{{ config_directory }}/btserver/opentracker.conf"

- name: copy torrent.ini conf file
  template:
    src: torrent.ini.j2
    dest: "{{ config_directory }}/btserver/torrent.ini"
  notify: 
    - Restart btserver container
    - Restart btserver_tracker container

- name: Ensuring btserver log directories exist
  file:
    path: "/var/log/btserver"
    state: "directory"
    mode: "0775"
  become: true

- name: Touch btserver log file and set permissions
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0644
    state: touch
  loop:
    - /var/log/btserver/torrent.log
    - /var/log/btserver/opentracker.log
