- name: Ensuring config directories exist
  file:
    path: "{{ config_directory }}/emqx"
    state: "directory"
    mode: "0770"
  become: true

- name: Copying over emqx.conf
  template:
    src: "emqx.conf.j2"
    dest: "{{ config_directory }}/emqx/emqx.conf"
    mode: "0660"
  become: true
  notify:
    - Restart emqx container

#- name: Copying over config.json files for services
#  template:
#    src: "{{ item.key }}.json.j2"
#    dest: "{{ config_directory }}/{{ item.key }}/config.json"
#    mode: "0660"
#  become: true
#  with_dict: "{{ emqx_services }}"
#  notify:
#    - "restart {{ item.key }} container"
