---
- name: Ensuring config directories exist
  file:
    path: "{{ config_directory }}/fsd"
    state: "directory"
    mode: "0770"
  become: true

- name: 生成 trochilus sql 文件
  template:
    src: trochilus.sql.j2
    dest: "{{ config_directory }}/fsd/trochilus.sql"
    owner: root
    mode: 0644

- name: Copying over fsd.conf
  template:
    src: "fsd{{ deploy_type }}.yml.j2"
    dest: "{{ config_directory }}/fsd/application-docker.yml"
    mode: "0660"
  become: true
  notify:
    - Restart fsd container

- name: Copying over fsd_nginx.conf
  template:
    src: "fsd_nginx.conf.j2"
    dest: "{{ config_directory }}/fsd/fsd.conf"
    mode: "0660"
  become: true
  notify:
    - Restart fsd-nginx container
