---
- name: Ensuring config directories exist
  file:
    path: "{{ config_directory }}/fsd"
    state: "directory"
    mode: "0770"
  become: true

- name: Get the node cidr
  shell: "ip r | egrep -v 'default' | egrep -v 'brq' | awk -F' '  '{print $1}'"
  register: cidr_address

- name: Get the cidr address
  set_fact:
    disable_subnets: "{{ cidr_address.stdout_lines | list | join(',') }}"

- name: Set init total_vdi_file_num var
  set_fact:
    total_vdi_file_num: 0

- name: 获取 vdi 文件总存储
  set_fact: 
    total_vdi_file_num: "{{ total_vdi_file_num | int + hostvars[item].vdi_storage_num | int }}"
  with_items: "{{ groups['storage'] }}"
  when: 
    - enable_local | bool
    - fsd_deploy_mode != "voi"

- name: Ensuring fsd_console config directories exist
  file:
    path: "{{ config_directory }}/fsd_console"
    state: "directory"
    mode: "0770"
  become: true

- name: 生成 trochilus sql 文件
  template:
    src: trochilus.sql.j2
    dest: "{{ config_directory }}/fsd/trochilus.sql"
    owner: root
    mode: 0644

- name: Create Tdesktop app dir
  file:
    path: "{{ share_disk_mount_path }}/static/vdiUpgradePackage/"
    state: "directory"
    mode: "0777"
    recurse: yes

- name: Copy change_ip.sh to fsd path
  become: true
  copy:
    src: change_ip.sh
    dest: "{{ config_directory }}/fsd/"
    mode: "0777"

- name: Copy Tdesktop.exe to share path
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ share_disk_mount_path }}/static/vdiUpgradePackage/"
    mode: "0644"
  with_items: "{{ tdesktop_edu_path_name }}"
  when:
    - deploy_edu | bool

- name: Copy Tdesktop.exe to share path
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ share_disk_mount_path }}/static/vdiUpgradePackage/"
    mode: "0644"
  with_items: "{{ tdesktop_path_name }}"
  when:
    - not only_deploy_voi | bool
    - deploy_comm | bool
  notify:
    - Restart fsd container

- name: Copying over fsd.conf
  template:
    src: "fsd{{ deploy_type }}.yml.j2"
    dest: "{{ config_directory }}/fsd/application-docker.yml"
    mode: "0660"
  become: true
  notify:
    - Restart fsd container

- name: Copying over fsd_nginx.conf
  template:
    src: "fsd{{ deploy_type }}_nginx.conf.j2"
    dest: "{{ config_directory }}/fsd/fsd.conf"
    mode: "0660"
  become: true
  notify:
    - Restart fsd-nginx container

- name: Copying over fsd_console_start script
  template:
    src: "fsd_console_start.sh.j2"
    dest: "{{ config_directory }}/fsd_console/fsd_console_start.sh"
    mode: "0777"
  become: true