---
- name: Ensuring config directories exist
  file:
    path: "{{ config_directory }}/fsd"
    state: "directory"
    mode: "0770"
  become: true

- name: 生成 trochilus sql 文件
  template:
    src: trochilus.sql.j2
    dest: "{{ config_directory }}/fsd/trochilus.sql"
    owner: root
    mode: 0644

- name: Create Tdesktop app dir
  file:
    path: "{{ desktop_mount_dir }}/static/vdiUpgradePackage/"
    state: "directory"
    mode: "0777"
    recurse: yes

- name: Copy Tdesktop.exe to share path
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ desktop_mount_dir }}/static/vdiUpgradePackage/"
    mode: "0644"
  with_items: "{{ tdesktop_path_name }}"
  when:
    - not only_deploy_voi | bool
    - deploy_comm | bool
  notify:
    - Restart fsd container

- name: Copying over fsd.conf
  template:
    src: "fsd{{ deploy_type }}.yml.j2"
    dest: "{{ config_directory }}/fsd/application-docker.yml"
    mode: "0660"
  become: true
  notify:
    - Restart fsd container

- name: Copying over fsd_nginx.conf
  template:
    src: "fsd_nginx.conf.j2"
    dest: "{{ config_directory }}/fsd/fsd.conf"
    mode: "0660"
  become: true
  notify:
    - Restart fsd-nginx container
