---
- name: Restart fsd-console-web container
  vars:
    service_name: "fsd-console-web"
    service: "{{ fsd_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    volumes: "{{ service.volumes }}"
    image: "{{ service.image }}"
    name: "{{ service.container_name }}"
    dimensions: "{{ service.dimensions }}"
    privileged: "{{ service.privileged | default(False) }}"
    command: "sh /opt/fsd_console_start/fsd_console_start.sh"
  run_once: True
  delegate_to: "{{ groups['fsd'][0] }}"