---
- name: Set init total_vcpus var
  set_fact:
    total_vcpus: 0

- name: Set init total_mems var
  set_fact:
    total_mems: 0
    node_mems: 0
    total_voi_mems: 0
    total_vdi_mems: 0

# cpu 每台暂定保留2
- name: Set total_vcpus var
  set_fact:
    total_vcpus: "{{ total_vcpus | int + (hostvars[item].ansible_processor_vcpus - reserved_host_cpus) * cpu_allocation_ratio }}"
  run_once: True
  with_items: "{{ groups['compute'] }}"

- name: 获取 osd 数量
  shell: systemctl | grep running | grep osd@ | wc -l
  register: osd_num
  when: enable_ceph | bool

- name: Set total_mems vars
  set_fact:
    total_mems: "{{ total_mems | int + ((hostvars[item].ansible_memtotal_mb  - reserved_osd_memory_mb * osd_num.stdout | int - reserved_mds_memory_mb - reserved_mon_memory_mb - reseverd_system_memory_mb - reserved_host_memory_mb) / 1024) | int }}"
  run_once: True
  with_items: "{{ groups['compute'] }}"
  when: enable_ceph | bool

- name: Set node_mems vars
  set_fact:
    node_mems: "{{ ((ansible_memtotal_mb  - reserved_osd_memory_mb * osd_num.stdout | int - reserved_mds_memory_mb - reserved_mon_memory_mb - reseverd_system_memory_mb - reserved_host_memory_mb) / 1024) | int }}"
  when: enable_ceph | bool

# 内存每台机器保留16
- name: Set total_mems vars
  set_fact:
    total_mems: "{{ total_mems | int + ((hostvars[item].ansible_memtotal_mb - reserved_host_memory_mb) / 1024)  | int }}"
  run_once: True
  with_items: "{{ groups['compute'] }}"
  when: not enable_ceph | bool

- name: Set node_mems vars
  set_fact:
    node_mems: "{{ ((ansible_memtotal_mb - reserved_host_memory_mb) / 1024) | int - voi_reserved_memory | int }}"
  when: not enable_ceph | bool

- name: Set total_mems vars
  set_fact:
    total_mems: "{% if hostvars[item].ansible_memtotal_mb > 8192 %}{{ total_mems | int +  8  }}{% else %}{{ total_mems | int + 4 }}{% endif %}"
  run_once: True
  with_items: "{{ groups['compute'] }}"
  when: hostvars[item].ansible_memtotal_mb <= 16384

- name: Set node_mems vars
  set_fact:
    node_mems: "{% if ansible_memtotal_mb > 8192 %}{{ 8 - voi_reserved_memory }}{% else %}{{ 4 - voi_reserved_memory }}{% endif %}"
  when: ansible_memtotal_mb <= 16384

- name: Set total_voi_mems vars
  set_fact:
    total_voi_mems: "{{ total_voi_mems | int + hostvars[item].voi_reserved_memory | int }}"
  run_once: True
  with_items: "{{ groups['compute'] }}"

- name: Set total_vdi_mems vars
  set_fact:
    total_vdi_mems: "{{ total_mems | int - total_voi_mems | int }}"
  run_once: True

# 获取 agent_uuid
- name: get agent uuid
  shell: cat /etc/klcloud/trochilus/trochilus-agent-lock
  register: agent_uuid

- name: Set agent uuid
  set_fact:
    agent_uuid: "{{ agent_uuid.stdout }}"
