---
- name: Ensuring libvirt config directories exist
  file:
    path: "{{ config_directory }}/libvirt"
    state: "directory"
    mode: "0775"
  become: true

- name: 复制 secrets 相关文件
  block:
    - name: 创建 secrets 目录
      file:
        path: "{{ config_directory }}/libvirt/secrets/"
        state: directory
        mode: 0755

    - name: Copy secrets xml 密钥 文件
      template:
        src: ceph.xml.j2
        dest: "{{ config_directory }}/libvirt/secrets/{{ ceph_rbd_secret_uuid }}.xml"
        owner: root
        mode: 0644

    - name: Copy secrets base64 密钥 文件
      template:
        src: ceph.base64.j2
        dest: "{{ config_directory }}/libvirt/secrets/{{ ceph_rbd_secret_uuid }}.base64"
        owner: root
        mode: 0644
  when:
    - enable_ceph | bool

- name: 创建 vdi 目录及文件
  block:
    - name: 创建 vdi 目录
      file:
        path: "{{ config_directory }}/libvirt/vdi/"
        state: directory
        mode: 0755

    - name: Copy vdi.ini 文件
      copy:
        src: vdi_conf.ini
        dest: "{{ config_directory }}/libvirt/vdi/vdi_conf.ini"
        owner: root
        mode: 0644
  when:
   - not only_deploy_voi | bool


- name: Copy libvirtd.conf 文件
  copy:
    src: libvirtd.conf
    dest: "{{ config_directory }}/libvirt/libvirtd.conf"
    owner: root
    mode: 0644

- name: Copy qemu.conf 文件
  copy:
    src: qemu.conf
    dest: "{{ config_directory }}/libvirt/qemu.conf"
    owner: root
    mode: 0644
  notify:
    - Restart libvirt container
