- import_tasks: "update_network.yml"

- import_tasks: "update_haproxy.yml"
  when: 
    - enable_haproxy | bool

- import_tasks: "update_keepalived.yml"
  when: 
    - enable_keepalived | bool

- import_tasks: "update_btserver.yml"
  when: 
    - enable_btserver | bool

- import_tasks: "update_seafile.yml"
  when: 
    - enable_seafile | bool

- import_tasks: "update_fsd_console_web.yml"

- import_tasks: "update_fsd_db.yml"

- name: Replace the IP in the host file
  replace:
    path: "{{ inventory_file }}"
    regexp: '{{ hostvars[item].external_manage_ip }}'
    replace: '{{ hostvars[item].new_external_manage_ip }}'
    backup: yes
  run_once: True
  delegate_to: "{{ groups['baremetal'][0] }}"
  with_items: "{{ groups['baremetal'] }}"

- name: Restart veth-setup service
  systemd:
    name: veth-setup.service
    state: restarted
    enabled: True
  when: enable_single_net | bool