fsd_services:
  fsd:
    enabled: True
    container_name: fsd
    image: "{{ fsd_image_full }}"
    volumes: "{{ fsd_default_volumes }}"
  fsd-job:
    enabled: True
    container_name: fsd_job
    image: "{{ fsd_job_image_full }}"
    volumes: "{{ fsd_job_default_volumes }}"
  fsd-nginx:
    enabled: True
    container_name: fsd_nginx
    image: "{{ fsd_nginx_image_full }}"
    volumes: "{{ fsd_nginx_default_volumes }}"
  fsd-init:
    enabled: False
    container_name: fsd_init
    image: "{{ fsd_init_image_full }}"
    environment:
      fsd_init_db_vip: "{{ internal_vip_address }}" 
      fsd_init_db_password: "{{ mariadb_root_password }}"


deploy_type: "{% if deploy_edu %}'_edu'{% else %}''{% endif %}"
####################
# fsd
####################
fsd_image: "{{ docker_image_repository }}/fsd{{ deploy_type }}"
fsd_tag: "{{ fsd_default_tag }}"
fsd_image_full: "{{ fsd_image }}:{{ fsd_tag }}"
fsd_default_volumes:
  - /var/lib/trochilus:/var/lib/trochilus:rw
  - "{{ config_directory }}/fsd/application-docker.yml:/home/static/java/application-docker.yml:rw"
  - "/etc/localtime:/etc/localtime:ro"

####################
# fsd-job
####################
fsd_job_image: "{{ docker_image_repository }}/fsd{{ deploy_type }}_job"
fsd_job_tag: "{{ fsd_default_tag }}"
fsd_job_image_full: "{{ fsd_job_image }}:{{ fsd_job_tag }}"
fsd_job_default_volumes: 
  - "/etc/localtime:/etc/localtime:ro"

####################
# fsd-nginx
####################
fsd_nginx_image: "{{ docker_image_repository }}/fsd{{ deploy_type }}_nginx"
fsd_nginx_tag: "{{ fsd_default_tag }}"
fsd_nginx_image_full: "{{ fsd_nginx_image }}:{{ fsd_nginx_tag }}"
fsd_nginx_default_volumes: 
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ config_directory }}/fsd/fsd.conf:/etc/nginx/conf/fsd.conf:rw"

####################
# fsd-init
####################
fsd_init_image: "{{ docker_image_repository }}/fsd{{ deploy_type }}_init"
fsd_init_tag: "{{ fsd_default_tag }}"
fsd_init_image_full: "{{ fsd_init_image }}:{{ fsd_init_tag }}"
fsd_init_default_volumes:
  - "/etc/localtime:/etc/localtime:ro"