fsd_services:
  fsd:
    enabled: True
    container_name: fsd
    image: "{{ fsd_image_full }}"
    volumes: "{% if deploy_edu %}{{ fsd_default_volumes + fsd_edu_volumes }}{% else %}{{ fsd_default_volumes }}{% endif %}"
    dimensions: "{{ fsd_dimensions }}"
    privileged: True
  fsd-job:
    enabled: True
    container_name: fsd_job
    image: "{{ fsd_job_image_full }}"
    volumes: "{{ fsd_job_default_volumes }}"
    environment:
      SERVER_PORT: "{{ fsd_listen_job_port }}"
      ENV_FSD_COMMON_JOB_MYSQL_SVC: "{{ default_internal_server_visit_ip }}" 
      ENV_FSD_COMMON_JOB_MYSQL_USERNAME: "{{ mariadb_root_username }}"
      ENV_FSD_COMMON_JOB_MYSQL_PASSWORD: "{{ mariadb_root_password }}"
    dimensions: "{{ fsd_dimensions }}"
    privileged: True
  fsd-nginx:
    enabled: True
    container_name: fsd_nginx
    image: "{{ fsd_nginx_image_full }}"
    volumes: "{{ fsd_nginx_default_volumes }}"
    dimensions: "{{ fsd_dimensions }}"
    privileged: True
  fsd-init:
    enabled: False
    container_name: fsd_init
    image: "{{ fsd_init_image_full }}"
    environment:
      fsd_init_db_vip: "{{ default_internal_server_visit_ip }}" 
      fsd_init_db_password: "{{ mariadb_root_password }}"
    dimensions: "{{ fsd_dimensions }}"
    privileged: True
  fsd-console-web:
    enabled: False
    container_name: fsd_console_web
    image: "{{ fsd_console_web_image_full }}"
    dimensions: "{{ fsd_dimensions }}"
    privileged: True

deploy_type: "{% if deploy_edu | bool %}_edu{% else %}{% endif %}"
deploy_storage_type: "{% if enable_lvm | bool %}lvm{% elif enable_ceph | bool %}ceph{% endif %}"
fsd_proxy_ip: "{% if proxy_ip != '' %}{{ proxy_ip }}{% elif enable_keepalived | bool %}{{ external_vip_address }}{% else %}{{ api_interface_address }}{% endif %}"
fsd_vip: "{% if enable_keepalived | bool %}{{ external_vip_address }}{% else %}{{ api_interface_address }}{% endif %}"
fsd_ngxin_proxy_pass: "{{ default_internal_server_visit_ip }}"
fsd_mysql_conn_ip: "{{ default_internal_server_visit_ip }}"
####################
# fsd
####################
fsd_image: "{{ docker_image_repository }}/fsd{{ deploy_type }}"
fsd_tag: "{{ fsd_default_tag }}"
fsd_image_full: "{{ fsd_image }}:{{ fsd_tag }}"
fsd_default_volumes:
  - "{{ desktop_mount_dir }}:{{ desktop_mount_dir }}:rw"
  - "{{ desktop_mount_dir }}/prometheus/rules:/home/static/prometheus/rules:rw"
  - "{{ desktop_mount_dir }}/prometheus/alertmanager/:/home/static/prometheus/alert/:rw"
  - "{{ config_directory }}/fsd/application-docker.yml:/home/static/java/application-docker.yml:rw"
  - "/var/log/fsd:/log:rw"
  - "/etc/localtime:/etc/localtime:ro"

fsd_edu_volumes:
  - "{{ config_directory }}/fsd/fsd.conf:/etc/nginx/conf/fsd.conf:rw"
  - "{{ config_directory }}/btserver/torrent.ini:/opt/torrent_server_bin/torrent.ini:rw"
  - "{{ config_directory }}/btserver/opentracker.conf:/opt/torrent_server_bin/opentracker.conf:rw"
  - "{{ config_directory }}/keepalived/conf.d/external.conf:/etc/keepalived/keepalived.conf:rw"
  - "{{ desktop_mount_dir }}/static:/var/www/html/static:rw"

####################
# fsd-job
####################
fsd_job_image: "{{ docker_image_repository }}/fsd{{ deploy_type }}_job"
fsd_job_tag: "{{ fsd_default_tag }}"
fsd_job_image_full: "{{ fsd_job_image }}:{{ fsd_job_tag }}"
fsd_job_default_volumes:
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ config_directory }}/fsd/application-docker.yml:/home/static/java/application-docker.yml:rw"

####################
# fsd-nginx
####################
fsd_nginx_image: "{{ docker_image_repository }}/fsd{{ deploy_type }}_nginx"
fsd_nginx_tag: "{{ fsd_default_tag }}"
fsd_nginx_image_full: "{{ fsd_nginx_image }}:{{ fsd_nginx_tag }}"
fsd_nginx_default_volumes: 
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ desktop_mount_dir }}:/mnt:rw"
  - "{{ desktop_mount_dir }}/static:/usr/local/dist/static:rw"
  - "{{ config_directory }}/fsd/fsd.conf:/etc/nginx/conf/fsd.conf:rw"

####################
# fsd-init
####################
fsd_init_image: "{{ docker_image_repository }}/fsd{{ deploy_type }}_init"
fsd_init_tag: "{{ fsd_default_tag }}"
fsd_init_image_full: "{{ fsd_init_image }}:{{ fsd_init_tag }}"
fsd_init_default_volumes:
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ desktop_mount_dir }}/static:/home/tmp:rw"
  - "{{ config_directory }}/fsd/trochilus.sql:/home/trochilus/trochilus.sql:rw"

####################
# fsd_console_web
####################
fsd_console_web_image: "{{ docker_image_repository }}/fsd_console_web"
fsd_console_web_tag: "{{ fsd_default_tag }}"
fsd_console_web_image_full: "{{ fsd_console_web_image }}:{{ fsd_console_web_tag }}"

fsd_dimensions: 
  ulimits: 
    nofile:
      soft: 65535
      hard: 65535
    nproc:
      soft: 65535
      hard: 65535