---
# defaults file for baremetal
project_name: "mariadb"

mariadb_services:
  mariadb:
    container_name: mariadb
    image: "{{ mariadb_image_full }}"
    volumes: "{{ mariadb_default_volumes }}"

mariadb_port: "{{ mariadb_listen_server_port }}"

database_user: "{{ mariadb_root_username }}"
database_password: "{{ mariadb_root_password }}"
############
# images
############
mariadb_image: "{{ docker_image_repository }}/mariadb"
mariadb_tag: "{{ mariadb_default_tag }}"
mariadb_image_full: "{{ mariadb_image }}:{{ mariadb_tag }}"
mariadb_service: "{{ mariadb_services['mariadb'] }}"

############
# volume
############
mariadb_default_volumes:
  - "{{ config_directory }}/mariadb/:/var/lib/config_files/:rw"
  - "/etc/localtime:/etc/localtime:ro"
  - "/var/log/mariadb/:/var/log/mariadb/:rw"
  - "mariadb:/var/lib/mysql"
  # - "log:/var/log/mariadb/"

mariadb_wsrap_ip: "{% if enable_keepalived | bool %}{{ inventory_hostname }}{% else %}127.0.0.1{% endif %}"
