---
- import_playbook: gather-facts.yml

- name: Apply role baremetal
  gather_facts: false
  hosts: baremetal
  roles:
    - { role: baremetal,
        tags: baremetal,
        when: enable_baremetal| bool }

- name: Apply role keepalived
  gather_facts: false
  hosts: keepalived
  roles:
    - { role: keepalived,
        tags: keepalived,
        when: enable_keepalived| bool }

- name: Apply role haproxy
  gather_facts: false
  hosts: haproxy
  roles:
    - { role: haproxy,
        tags: haproxy,
        when: enable_haproxy| bool }

- name: Apply role mariadb
  gather_facts: false
  hosts: mariadb
  roles:
    - { role: mariadb,
        tags: mariadb,
        when: enable_mariadb| bool }

- name: Apply role redis
  gather_facts: false
  hosts: redis
  roles:
    - { role: redis,
        tags: redis,
        when: enable_redis| bool }

- name: Apply role emqx
  gather_facts: false
  hosts: emqx
  roles:
    - { role: emqx,
        tags: emqx,
        when: enable_emqx| bool }

- name: Apply role libvirt
  gather_facts: false
  hosts: libvirt
  roles:
    - { role: libvirt,
        tags: libvirt,
        when: enable_libvirt| bool }

- name: Apply role trochilus
  gather_facts: false
  hosts:
    - trochilus-api
    - trochilus-agent
  roles:
    - { role: trochilus,
        tags: trochilus,
        when: enable_trochilus| bool }

- name: Apply role websockify
  gather_facts: false
  hosts:
    - websockify
  roles:
    - { role: websockify,
        tags: websockify,
        when: enable_websockify| bool }

- name: Apply role prometheus
  gather_facts: false
  hosts:
    - prometheus
    - prometheus-node-exporter
    - prometheus-collectd-exporter
    - prometheus-host-exporter
  roles:
    - { role: prometheus,
        tags: prometheus,
        when: enable_prometheus| bool }

- name: Apply role guest-service
  gather_facts: false
  hosts: libvirt
  roles:
   - { role: guest-service,
       tags: guest-service,
       when: enable_guest_service| bool }

- name: Apply role btserver
  gather_facts: false
  hosts: btserver
  roles:
    - { role: btserver,
        tags: btserver,
        when: enable_btserver| bool }

- name: Apply role fsd
  gather_facts: false
  hosts: fsd
  roles:
    - { role: fsd,
        tags: fsd,
        when: enable_fsd| bool }
