---
- name: Restart redis container
  become: true
  vars:
    service_name: "redis"
    service: "{{ redis_services[service_name] }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
    command: "redis-server /etc/redis/redis.conf"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  # listen: Restart redis and redis-sentinel container

- name: Restart redis-sentinel container
  become: true
  vars:
    service_name: "redis-sentinel"
    service: "{{ redis_services[service_name] }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
    command: "redis-sentinel /etc/redis/redis.conf"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  # listen: Restart redis and redis-sentinel container
