- name: Get partition list
  shell: "ls {{ system_device }}*"
  register: partition_list

- name: Determine last partition number
  set_fact:
    partition_num: "{{ partition_list.stdout_lines[-1][-1] }}"
  when: partition_list.stdout_lines | length > 0

- name: Get last partition mount point
  shell: "lsblk -n -o MOUNTPOINT {{ system_device }}{{ partition_num }}"
  register: last_partition_mount
  when: partition_num is defined

- name: print last_partition_mount
  debug: var=last_partition_mount

- name: Delete data partition
  shell: "parted {{ system_device }} rm {{ partition_num }}"
  when: 
    - partition_num is defined 
    - last_partition_mount.stdout_lines | length == 0
