---
- include_tasks: validate_docker_execute.yml

- include_tasks: cleanup_vms.yml

- include_tasks: cleanup_containers.yml

- include_tasks: cleanup_desktop_res.yml

- include_tasks: cleanup_volume.yml
  when:
    - enable_local | bool

- name: Delete trochilus dir file
  shell: rm -rf {{ share_disk_mount_path }}/*
  when:
    - enable_ceph | bool

- name: Umount cephfs share dir
  mount:
    path: "{{ share_disk_mount_path }}"
    state: absent
  ignore_errors: True
  when:
    - enable_ceph | bool

- name: 清理 vg 卷
  shell: vgremove -y {{ lvm_volgroup_name }}
  when:
    - enable_lvm | bool
  ignore_errors: True

- name: 生成清理命令
  set_fact:
    pv_volume: "{% for pv in lvm_pv_device %} {{ pv }} {% if not loop.last %} {% endif %}{% endfor %}"
  when:
    - enable_lvm | bool

- name: 清理 pv 卷
  become: true
  ignore_errors: True
  shell: pvremove -y {{ pv_volume }}
  when:
    - enable_lvm | bool

- include_tasks: cleanup_partition.yml
  when:
    - local_device | length == 0
    - ceph_volume_data | length == 0
    
- name: 清除清除系统缓存的定时任务
  cron:
    name: "clean linux cache"
    state: absent
  when: inventory_hostname in groups["control"]
  ignore_errors: true

- name: 清理 iptables
  shell: "{{ item }} || true"
  with_items:
  - iptables -F
  - iptables -X
  - iptables -F -t nat
  - iptables -X -t nat
  - iptables -F -t filter
  - iptables -X -t filter
  - iptables -F -t mangle
  - iptables -X -t mangle

- name: 刷新 iptables
  iptables:
    table: "{{ item }}"
    flush: yes
  with_items:
    - filter
    - nat
    - mangle

- name: 获取 trochilus 创建的网络 namespace
  shell: ip netns | awk -F' ' '{print $1}'
  register: trochilus_netns

- name: 删除网络命名空间
  shell: ip netns del {{ item }}
  with_items: "{{ trochilus_netns.stdout_lines }}"

- name: 查看 coredump file 是否挂载
  shell: "mountpoint -q {{ coredump_libvirt_path }}"
  register: coredump_check
  ignore_errors: true

- name: 取消挂载 coredump 文件
  shell: "umount {{ coredump_libvirt_path }}"
  when:
    - coredump_check.rc == 0

- name: 删除 coredump 文件
  shell: "rm -rf {{ coredump_img_file_path }}/coredump.img"
  when:
    - coredump_check.rc == 0

- name: 取消挂载 coredump 文件
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^{{ coredump_img_file_path }}/coredump.img'

- name: 关闭 swap 分区
  shell: swapoff -a
  when:
    - create_swap_file | bool 

- name: 删除 coredump 文件
  shell: "rm -rf {{ swap_file_path }}"
  when:
    - create_swap_file | bool 

- name: 取消挂载 swap 文件
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^{{ swap_file_path }}'
  when:
    - create_swap_file | bool
  
- name: 移除添加的 hosts 信息
  blockinfile:
    path: "/etc/hosts"
    state: absent
    marker: "# {mark} ANSIBLE GENERATED HOSTS"

- name: 移除 logs 信息
  shell: "rm -rf /var/log/{{ item }}"
  with_items:
    - "trochilus"
    - "fsd"
    - "guest-service"
    - "emqx"
    - "mariadb"
    - "redis"

- name: 重启网络
  systemd:
    name: NetworkManager
    state: restarted

- name: 重启docker
  systemd:
    name: docker
    state: restarted
  ignore_errors: true
